# Generated by Django 5.2 on 2025-11-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"managed": False},
        ),
    ]
