# Generated by Django 5.2 on 2025-11-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_auditlog_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="auditlog",
            table="audit_logs",
        ),
    ]
