# Generated by Django 5.2.6 on 2025-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='drug_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='ham_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='legitimate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='phishing_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='safe_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='spam_score',
            field=models.FloatField(default=0.0),
        ),
    ]
