# Generated by Django 5.2 on 2025-11-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0003_moderationresult_drug_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationresult",
            name="non_toxic_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="moderationresult",
            name="toxic_score",
            field=models.FloatField(default=0.0),
        ),
    ]
