# Generated by Django 5.2 on 2025-11-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0005_rename_notes_feedback_moderator_notes_slangword"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="moderationresult",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="slangword",
            options={"managed": False},
        ),
    ]
