# Generated by Django 5.2 on 2025-11-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0006_alter_content_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slangword",
            options={"managed": False, "ordering": ["-created_at"]},
        ),
        migrations.AlterModelTable(
            name="content",
            table="contents",
        ),
        migrations.AlterModelTable(
            name="feedback",
            table="feedbacks",
        ),
        migrations.AlterModelTable(
            name="moderationresult",
            table="moderation_results",
        ),
        migrations.AlterModelTable(
            name="slangword",
            table="slang_words",
        ),
    ]
